import { MigrationInterface, QueryRunner } from "typeorm";

export class Initial.ts1784354610885 implements MigrationInterface {
    name = 'Initial.ts1784354610885'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "roles" ADD "key" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "UQ_a87cf0659c3ac379b339acf36a2" UNIQUE ("key")`);
        await queryRunner.query(`ALTER TABLE "states" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_module"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "module"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_module_enum"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "module" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "action"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "action" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "entity_type"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_entity_type_enum"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "entity_type" character varying(100)`);
        await queryRunner.query(`DROP INDEX "public"."idx_plan_review_assignment_review_status"`);
        await queryRunner.query(`ALTER TYPE "public"."plan_review_assignments_status_enum" RENAME TO "plan_review_assignments_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."plan_review_assignments_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', 'UNDER_REVIEW')`);
        await queryRunner.query(`ALTER TABLE "plan_review_assignments" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "plan_review_assignments" ALTER COLUMN "status" TYPE "public"."plan_review_assignments_status_enum" USING "status"::"text"::"public"."plan_review_assignments_status_enum"`);
        await queryRunner.query(`ALTER TABLE "plan_review_assignments" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."plan_review_assignments_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."plan_reviews_status_enum" RENAME TO "plan_reviews_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."plan_reviews_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'UNDER_REVIEW', 'CHANGES_REQUESTED')`);
        await queryRunner.query(`ALTER TABLE "plan_reviews" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "plan_reviews" ALTER COLUMN "status" TYPE "public"."plan_reviews_status_enum" USING "status"::"text"::"public"."plan_reviews_status_enum"`);
        await queryRunner.query(`ALTER TABLE "plan_reviews" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."plan_reviews_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."plan_versions_status_enum" RENAME TO "plan_versions_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."plan_versions_status_enum" AS ENUM('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'PUBLISHED', 'ARCHIVED', 'SUBMITTED', 'UNDER_REVIEW')`);
        await queryRunner.query(`ALTER TABLE "plan_versions" ALTER COLUMN "status" TYPE "public"."plan_versions_status_enum" USING "status"::"text"::"public"."plan_versions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."plan_versions_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "plan_versions" DROP COLUMN "plan_type"`);
        await queryRunner.query(`CREATE TYPE "public"."plan_versions_plan_type_enum" AS ENUM('all-access', 'state', 'country', 'category', 'bundle')`);
        await queryRunner.query(`ALTER TABLE "plan_versions" ADD "plan_type" "public"."plan_versions_plan_type_enum" NOT NULL DEFAULT 'all-access'`);
        await queryRunner.query(`DROP INDEX "public"."idx_export_jobs_status_created"`);
        await queryRunner.query(`ALTER TYPE "public"."export_jobs_status_enum" RENAME TO "export_jobs_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."export_jobs_status_enum" AS ENUM('PENDING', 'RUNNING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'EXPIRED')`);
        await queryRunner.query(`ALTER TABLE "export_jobs" ALTER COLUMN "status" TYPE "public"."export_jobs_status_enum" USING "status"::"text"::"public"."export_jobs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."export_jobs_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."export_jobs_export_type_enum" RENAME TO "export_jobs_export_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."export_jobs_export_type_enum" AS ENUM('tender', 'users', 'subscriptions', 'financial')`);
        await queryRunner.query(`ALTER TABLE "export_jobs" ALTER COLUMN "export_type" TYPE "public"."export_jobs_export_type_enum" USING "export_type"::"text"::"public"."export_jobs_export_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."export_jobs_export_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "export_jobs" ALTER COLUMN "filters" SET DEFAULT '{}'::jsonb`);
        await queryRunner.query(`ALTER TYPE "public"."notification_actions_type_enum" RENAME TO "notification_actions_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."notification_actions_type_enum" AS ENUM('REDIRECT', 'API_POST', 'MODAL', 'DOWNLOAD', 'APPROVE', 'REJECT', 'TENDER_APPROVE', 'TENDER_REJECT', 'TENDER_PUBLISH', 'TENDER_ARCHIVE', 'ROLE_APPROVE', 'ROLE_REJECT', 'ROLE_PUBLISH', 'ROLE_ARCHIVE')`);
        await queryRunner.query(`ALTER TABLE "notification_actions" ALTER COLUMN "type" TYPE "public"."notification_actions_type_enum" USING "type"::"text"::"public"."notification_actions_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notification_actions_type_enum_old"`);
        await queryRunner.query(`DROP INDEX "public"."idx_role_review_assignment_review_status"`);
        await queryRunner.query(`ALTER TYPE "public"."role_review_assignments_status_enum" RENAME TO "role_review_assignments_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."role_review_assignments_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', 'UNDER_REVIEW')`);
        await queryRunner.query(`ALTER TABLE "role_review_assignments" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "role_review_assignments" ALTER COLUMN "status" TYPE "public"."role_review_assignments_status_enum" USING "status"::"text"::"public"."role_review_assignments_status_enum"`);
        await queryRunner.query(`ALTER TABLE "role_review_assignments" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."role_review_assignments_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "role_review_comments" DROP CONSTRAINT "FK_4ae6557064b0a53fff244789948"`);
        await queryRunner.query(`ALTER TABLE "role_review_comments" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."role_reviews_status_enum" RENAME TO "role_reviews_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."role_reviews_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'UNDER_REVIEW', 'CHANGES_REQUESTED')`);
        await queryRunner.query(`ALTER TABLE "role_reviews" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "role_reviews" ALTER COLUMN "status" TYPE "public"."role_reviews_status_enum" USING "status"::"text"::"public"."role_reviews_status_enum"`);
        await queryRunner.query(`ALTER TABLE "role_reviews" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."role_reviews_status_enum_old"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notification_recipients_role_status_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notification_recipients_user_status_date"`);
        await queryRunner.query(`ALTER TYPE "public"."notification_recipients_status_enum" RENAME TO "notification_recipients_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."notification_recipients_status_enum" AS ENUM('UNREAD', 'READ', 'ARCHIVED', 'DISMISSED')`);
        await queryRunner.query(`ALTER TABLE "notification_recipients" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "notification_recipients" ALTER COLUMN "status" TYPE "public"."notification_recipients_status_enum" USING "status"::"text"::"public"."notification_recipients_status_enum"`);
        await queryRunner.query(`ALTER TABLE "notification_recipients" ALTER COLUMN "status" SET DEFAULT 'UNREAD'`);
        await queryRunner.query(`DROP TYPE "public"."notification_recipients_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."notifications_category_enum" RENAME TO "notifications_category_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_category_enum" AS ENUM('SYSTEM', 'TENDER', 'BILLING', 'SECURITY', 'WORKSPACE', 'REVIEW', 'ROLE')`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "category" TYPE "public"."notifications_category_enum" USING "category"::"text"::"public"."notifications_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_category_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."notifications_severity_enum" RENAME TO "notifications_severity_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_severity_enum" AS ENUM('INFO', 'WARNING', 'CRITICAL', 'HIGH', 'MEDIUM')`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "severity" TYPE "public"."notifications_severity_enum" USING "severity"::"text"::"public"."notifications_severity_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_severity_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."permissions_action_enum" RENAME TO "permissions_action_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."permissions_action_enum" AS ENUM('view', 'create', 'update', 'delete', 'approve', 'reject', 'publish', 'unpublish', 'archive', 'unarchive', 'restore', 'export', 'import', 'manage', 'custom', 'review', 'assign', 'compare', 'audit_view', 'block', 'unblock', 'remove', 'suspend', 'unsuspend', 'activate', 'deactivate')`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "action" TYPE "public"."permissions_action_enum" USING "action"::"text"::"public"."permissions_action_enum"`);
        await queryRunner.query(`DROP TYPE "public"."permissions_action_enum_old"`);
        await queryRunner.query(`ALTER TABLE "scheduled_reports" ALTER COLUMN "filters" SET DEFAULT '{}'::jsonb`);
        await queryRunner.query(`ALTER TABLE "user_dashboard_layouts" ALTER COLUMN "widgets" SET DEFAULT '[]'::jsonb`);
        await queryRunner.query(`ALTER TABLE "user_dashboard_layouts" ALTER COLUMN "filters" SET DEFAULT '{}'::jsonb`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ef8320c2a2c72852adda5d68c5"`);
        await queryRunner.query(`ALTER TYPE "public"."users_account_type_enum" RENAME TO "users_account_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_account_type_enum" AS ENUM('user', 'admin', 'system')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "account_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "account_type" TYPE "public"."users_account_type_enum" USING "account_type"::"text"::"public"."users_account_type_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "account_type" SET DEFAULT 'user'`);
        await queryRunner.query(`DROP TYPE "public"."users_account_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "company_name" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."users_status_enum" RENAME TO "users_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('pending_email_verification', 'pending_approval', 'active', 'rejected', 'suspended', 'deactivated', 'archived', 'BLOCKED', 'rejected_by_admin', 'APPROVED')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" TYPE "public"."users_status_enum" USING "status"::"text"::"public"."users_status_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" SET DEFAULT 'pending_email_verification'`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."security_logs_event_enum" RENAME TO "security_logs_event_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."security_logs_event_enum" AS ENUM('LOGIN_SUCCESS', 'user_login', 'LOGIN_FAILED', 'LOGOUT', 'PASSWORD_RESET_REQUESTED', 'PASSWORD_RESET_COMPLETED', 'PASSWORD_CHANGED', 'MFA_ENABLED', 'MFA_DISABLED', 'MFA_FAILED', 'ACCOUNT_LOCKED', 'ACCOUNT_UNLOCKED', 'TOKEN_REFRESHED', 'UNAUTHORIZED_ACCESS', 'SUSPICIOUS_ACTIVITY', 'TWO_FACTOR_ENABLED', 'TWO_FACTOR_DISABLED', 'PROFILE_UPDATED', 'ACCOUNT_DEACTIVATED', 'ACCOUNT_REACTIVATED', 'ACCOUNT_DELETE_REQUESTED', 'RESEND_VERIFICATION_SUCCESS', 'REGISTER_SUCCESS', 'CAPTCHA_FAILED', 'PASSWORD_CHANGE', 'EMAIL_CHANGE_REQUEST', 'EMAIL_CHANGE_SUCCESS', 'EMAIL_CHANGE_VERIFY', 'ADMIN_REGISTER_SUCCESS')`);
        await queryRunner.query(`ALTER TABLE "security_logs" ALTER COLUMN "event" TYPE "public"."security_logs_event_enum" USING "event"::"text"::"public"."security_logs_event_enum"`);
        await queryRunner.query(`DROP TYPE "public"."security_logs_event_enum_old"`);
        await queryRunner.query(`ALTER TABLE "subscription_migrations" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."subscription_migrations_status_enum" AS ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED')`);
        await queryRunner.query(`ALTER TABLE "subscription_migrations" ADD "status" "public"."subscription_migrations_status_enum" NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_module" ON "audit_logs" ("module") `);
        await queryRunner.query(`CREATE INDEX "idx_plan_review_assignment_review_status" ON "plan_review_assignments" ("review_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_export_jobs_status_created" ON "export_jobs" ("status", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_role_review_assignment_review_status" ON "role_review_assignments" ("review_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "roles_key_idx" ON "roles" ("key") `);
        await queryRunner.query(`CREATE INDEX "idx_notification_recipients_role_status_date" ON "notification_recipients" ("role_id", "status", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_notification_recipients_user_status_date" ON "notification_recipients" ("user_id", "status", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_ef8320c2a2c72852adda5d68c5" ON "users" ("account_type", "status") `);
        await queryRunner.query(`ALTER TABLE "role_review_comments" ADD CONSTRAINT "FK_4ae6557064b0a53fff244789948" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_review_comments" DROP CONSTRAINT "FK_4ae6557064b0a53fff244789948"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ef8320c2a2c72852adda5d68c5"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notification_recipients_user_status_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notification_recipients_role_status_date"`);
        await queryRunner.query(`DROP INDEX "public"."roles_key_idx"`);
        await queryRunner.query(`DROP INDEX "public"."idx_role_review_assignment_review_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_export_jobs_status_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_plan_review_assignment_review_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_module"`);
        await queryRunner.query(`ALTER TABLE "subscription_migrations" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_migrations_status_enum"`);
        await queryRunner.query(`ALTER TABLE "subscription_migrations" ADD "status" character varying(50) NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`CREATE TYPE "public"."security_logs_event_enum_old" AS ENUM('LOGIN_SUCCESS', 'LOGIN_FAILED', 'LOGOUT', 'PASSWORD_RESET_REQUESTED', 'PASSWORD_RESET_COMPLETED', 'PASSWORD_CHANGED', 'MFA_ENABLED', 'MFA_DISABLED', 'MFA_FAILED', 'ACCOUNT_LOCKED', 'ACCOUNT_UNLOCKED', 'TOKEN_REFRESHED', 'UNAUTHORIZED_ACCESS', 'SUSPICIOUS_ACTIVITY')`);
        await queryRunner.query(`ALTER TABLE "security_logs" ALTER COLUMN "event" TYPE "public"."security_logs_event_enum_old" USING "event"::"text"::"public"."security_logs_event_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."security_logs_event_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."security_logs_event_enum_old" RENAME TO "security_logs_event_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum_old" AS ENUM('pending_email_verification', 'pending_approval', 'active', 'rejected', 'suspended', 'deactivated', 'archived')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" TYPE "public"."users_status_enum_old" USING "status"::"text"::"public"."users_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" SET DEFAULT 'pending_email_verification'`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."users_status_enum_old" RENAME TO "users_status_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "company_name" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."users_account_type_enum_old" AS ENUM('user', 'admin')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "account_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "account_type" TYPE "public"."users_account_type_enum_old" USING "account_type"::"text"::"public"."users_account_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "account_type" SET DEFAULT 'user'`);
        await queryRunner.query(`DROP TYPE "public"."users_account_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."users_account_type_enum_old" RENAME TO "users_account_type_enum"`);
        await queryRunner.query(`CREATE INDEX "IDX_ef8320c2a2c72852adda5d68c5" ON "users" ("account_type", "status") `);
        await queryRunner.query(`ALTER TABLE "user_dashboard_layouts" ALTER COLUMN "filters" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "user_dashboard_layouts" ALTER COLUMN "widgets" SET DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "scheduled_reports" ALTER COLUMN "filters" SET DEFAULT '{}'`);
        await queryRunner.query(`CREATE TYPE "public"."permissions_action_enum_old" AS ENUM('view', 'create', 'update', 'delete', 'approve', 'reject', 'publish', 'archive', 'restore', 'export', 'import', 'manage', 'custom')`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "action" TYPE "public"."permissions_action_enum_old" USING "action"::"text"::"public"."permissions_action_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."permissions_action_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."permissions_action_enum_old" RENAME TO "permissions_action_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_severity_enum_old" AS ENUM('INFO', 'WARNING', 'CRITICAL')`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "severity" TYPE "public"."notifications_severity_enum_old" USING "severity"::"text"::"public"."notifications_severity_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_severity_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."notifications_severity_enum_old" RENAME TO "notifications_severity_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_category_enum_old" AS ENUM('SYSTEM', 'TENDER', 'BILLING', 'SECURITY', 'WORKSPACE')`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "category" TYPE "public"."notifications_category_enum_old" USING "category"::"text"::"public"."notifications_category_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_category_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."notifications_category_enum_old" RENAME TO "notifications_category_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."notification_recipients_status_enum_old" AS ENUM('UNREAD', 'READ', 'ARCHIVED')`);
        await queryRunner.query(`ALTER TABLE "notification_recipients" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "notification_recipients" ALTER COLUMN "status" TYPE "public"."notification_recipients_status_enum_old" USING "status"::"text"::"public"."notification_recipients_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "notification_recipients" ALTER COLUMN "status" SET DEFAULT 'UNREAD'`);
        await queryRunner.query(`DROP TYPE "public"."notification_recipients_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."notification_recipients_status_enum_old" RENAME TO "notification_recipients_status_enum"`);
        await queryRunner.query(`CREATE INDEX "idx_notification_recipients_user_status_date" ON "notification_recipients" ("created_at", "status", "user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_notification_recipients_role_status_date" ON "notification_recipients" ("created_at", "role_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."role_reviews_status_enum_old" AS ENUM('PENDING', 'APPROVED', 'REJECTED')`);
        await queryRunner.query(`ALTER TABLE "role_reviews" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "role_reviews" ALTER COLUMN "status" TYPE "public"."role_reviews_status_enum_old" USING "status"::"text"::"public"."role_reviews_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "role_reviews" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."role_reviews_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."role_reviews_status_enum_old" RENAME TO "role_reviews_status_enum"`);
        await queryRunner.query(`ALTER TABLE "role_review_comments" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "role_review_comments" ADD CONSTRAINT "FK_4ae6557064b0a53fff244789948" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`CREATE TYPE "public"."role_review_assignments_status_enum_old" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED')`);
        await queryRunner.query(`ALTER TABLE "role_review_assignments" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "role_review_assignments" ALTER COLUMN "status" TYPE "public"."role_review_assignments_status_enum_old" USING "status"::"text"::"public"."role_review_assignments_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "role_review_assignments" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."role_review_assignments_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."role_review_assignments_status_enum_old" RENAME TO "role_review_assignments_status_enum"`);
        await queryRunner.query(`CREATE INDEX "idx_role_review_assignment_review_status" ON "role_review_assignments" ("review_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."notification_actions_type_enum_old" AS ENUM('REDIRECT', 'API_POST', 'MODAL', 'DOWNLOAD', 'APPROVE', 'REJECT')`);
        await queryRunner.query(`ALTER TABLE "notification_actions" ALTER COLUMN "type" TYPE "public"."notification_actions_type_enum_old" USING "type"::"text"::"public"."notification_actions_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."notification_actions_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."notification_actions_type_enum_old" RENAME TO "notification_actions_type_enum"`);
        await queryRunner.query(`ALTER TABLE "export_jobs" ALTER COLUMN "filters" SET DEFAULT '{}'`);
        await queryRunner.query(`CREATE TYPE "public"."export_jobs_export_type_enum_old" AS ENUM('tender', 'users', 'subscriptions')`);
        await queryRunner.query(`ALTER TABLE "export_jobs" ALTER COLUMN "export_type" TYPE "public"."export_jobs_export_type_enum_old" USING "export_type"::"text"::"public"."export_jobs_export_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."export_jobs_export_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."export_jobs_export_type_enum_old" RENAME TO "export_jobs_export_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."export_jobs_status_enum_old" AS ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'EXPIRED')`);
        await queryRunner.query(`ALTER TABLE "export_jobs" ALTER COLUMN "status" TYPE "public"."export_jobs_status_enum_old" USING "status"::"text"::"public"."export_jobs_status_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."export_jobs_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."export_jobs_status_enum_old" RENAME TO "export_jobs_status_enum"`);
        await queryRunner.query(`CREATE INDEX "idx_export_jobs_status_created" ON "export_jobs" ("created_at", "status") `);
        await queryRunner.query(`ALTER TABLE "plan_versions" DROP COLUMN "plan_type"`);
        await queryRunner.query(`DROP TYPE "public"."plan_versions_plan_type_enum"`);
        await queryRunner.query(`ALTER TABLE "plan_versions" ADD "plan_type" character varying(50) NOT NULL DEFAULT 'all-access'`);
        await queryRunner.query(`CREATE TYPE "public"."plan_versions_status_enum_old" AS ENUM('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'PUBLISHED', 'ARCHIVED')`);
        await queryRunner.query(`ALTER TABLE "plan_versions" ALTER COLUMN "status" TYPE "public"."plan_versions_status_enum_old" USING "status"::"text"::"public"."plan_versions_status_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."plan_versions_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."plan_versions_status_enum_old" RENAME TO "plan_versions_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."plan_reviews_status_enum_old" AS ENUM('PENDING', 'APPROVED', 'REJECTED')`);
        await queryRunner.query(`ALTER TABLE "plan_reviews" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "plan_reviews" ALTER COLUMN "status" TYPE "public"."plan_reviews_status_enum_old" USING "status"::"text"::"public"."plan_reviews_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "plan_reviews" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."plan_reviews_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."plan_reviews_status_enum_old" RENAME TO "plan_reviews_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."plan_review_assignments_status_enum_old" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED')`);
        await queryRunner.query(`ALTER TABLE "plan_review_assignments" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "plan_review_assignments" ALTER COLUMN "status" TYPE "public"."plan_review_assignments_status_enum_old" USING "status"::"text"::"public"."plan_review_assignments_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "plan_review_assignments" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."plan_review_assignments_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."plan_review_assignments_status_enum_old" RENAME TO "plan_review_assignments_status_enum"`);
        await queryRunner.query(`CREATE INDEX "idx_plan_review_assignment_review_status" ON "plan_review_assignments" ("review_id", "status") `);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "entity_type"`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_entity_type_enum" AS ENUM('USER', 'CATEGORY', 'TENDER', 'SUBSCRIPTION', 'PAYMENT', 'PERMISSION', 'ROLE', 'ORGANIZATION')`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "entity_type" "public"."audit_logs_entity_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "action"`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'APPROVE', 'REJECT', 'EXPORT', 'DOWNLOAD')`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "action" "public"."audit_logs_action_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "module"`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_module_enum" AS ENUM('AUTH', 'USER', 'RBAC', 'TENDER', 'CATEGORY', 'PAYMENT', 'SYSTEM', 'NOTIFICATION', 'CMS', 'SUBSCRIPTION')`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "module" "public"."audit_logs_module_enum" NOT NULL`);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_module" ON "audit_logs" ("module") `);
        await queryRunner.query(`ALTER TABLE "states" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "UQ_a87cf0659c3ac379b339acf36a2"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "key"`);
    }

}
