// src/database/seeds/rbac/permissions/analytics.seed.ts

export const analyticsPermissions = [
  {
    key: 'analytics.view',
    name: 'View BI Overview',
    action: 'view',
    description: 'View dashboard overview, general tenders and categories distribution.',
    displayOrder: 1,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    key: 'analytics.export',
    name: 'Export BI Data',
    action: 'export',
    description: 'Initiate asynchronous data exports for reports.',
    displayOrder: 2,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    key: 'analytics.financial',
    name: 'View Financial Analytics',
    action: 'view_financial',
    description: 'Access billing summaries, ARR/MRR trends, and revenue collections.',
    displayOrder: 3,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    key: 'analytics.users',
    name: 'View User Analytics',
    action: 'view_users',
    description: 'View customer registrations, active account types, and user sessions.',
    displayOrder: 4,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    key: 'analytics.vendors',
    name: 'View Vendor Analytics',
    action: 'view_vendors',
    description: 'Access vendor performance charts, bid win ratios, and leaderboards.',
    displayOrder: 5,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    key: 'analytics.system',
    name: 'View System Analytics',
    action: 'view_system',
    description: 'View server latency, queue depth, cache hits, and background execution logs.',
    displayOrder: 6,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    key: 'analytics.reports',
    name: 'Manage Scheduled Reports',
    action: 'manage_reports',
    description: 'Configure and automate report emails to roles or webhooks.',
    displayOrder: 7,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    key: 'analytics.ai',
    name: 'Access AI Insights',
    action: 'access_ai',
    description: 'Receive predictions, churn forecasting, and procurement demand suggestions.',
    displayOrder: 8,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
];
