// src/database/seeds/rbac/permissions/system.seed.ts

export const systemPermissions = [
    {
        key: 'system.view',
        name: 'View System',
        action: 'view',
        description: 'View system configuration and status.',
        displayOrder: 1,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },

    {
        key: 'system.settings.manage',
        name: 'Manage Settings',
        action: 'manage',
        description: 'Manage application settings.',
        displayOrder: 2,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },

    {
        key: 'system.feature_flags.manage',
        name: 'Manage Feature Flags',
        action: 'manage',
        description: 'Enable or disable application feature flags.',
        displayOrder: 3,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },

    {
        key: 'system.maintenance.manage',
        name: 'Manage Maintenance Mode',
        action: 'manage',
        description: 'Enable or disable maintenance mode.',
        displayOrder: 4,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },

    {
        key: 'system.job.manage',
        name: 'Manage Background Jobs',
        action: 'manage',
        description: 'Run, stop and monitor background jobs.',
        displayOrder: 5,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },

    {
        key: 'system.cache.manage',
        name: 'Manage Cache',
        action: 'manage',
        description: 'Clear and rebuild application caches.',
        displayOrder: 6,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },

    {
        key: 'system.backup.manage',
        name: 'Manage Backups',
        action: 'manage',
        description: 'Create and restore application backups.',
        displayOrder: 7,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },

    {
        key: 'system.storage.manage',
        name: 'Manage Storage',
        action: 'manage',
        description: 'Manage uploaded files and storage configuration.',
        displayOrder: 8,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },

    {
        key: 'system.email.manage',
        name: 'Manage Email Configuration',
        action: 'manage',
        description: 'Configure SMTP and email settings.',
        displayOrder: 9,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },

    {
        key: 'system.payment.manage',
        name: 'Manage Payment Gateways',
        action: 'manage',
        description: 'Configure payment gateway providers and credentials.',
        displayOrder: 10,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },

    {
        key: 'system.api.manage',
        name: 'Manage API Keys',
        action: 'manage',
        description: 'Manage API keys and third-party integrations.',
        displayOrder: 11,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },

    {
        key: 'system.security.manage',
        name: 'Manage Security',
        action: 'manage',
        description: 'Manage security policies and authentication settings.',
        displayOrder: 12,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },

    {
        key: 'system.initialize',
        name: 'Initialize System',
        action: 'initialize',
        description: 'Run one-time application initialization.',
        displayOrder: 13,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },

    {
        key: 'system.health.view',
        name: 'View System Health',
        action: 'view',
        description: 'View system health, queues and service status.',
        displayOrder: 14,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },

    {
        key: 'system.version.view',
        name: 'View System Version',
        action: 'view',
        description: 'View deployed application version and build information.',
        displayOrder: 15,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },
];