// src/database/seeds/rbac/permissions/tenders.seed.ts

export const tendersPermissions = [
    {
        key: 'tender.view',
        name: 'View Tenders',
        action: 'view',
        description: 'View tenders and tender details.',
        displayOrder: 1,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },

    {
        key: 'tender.create',
        name: 'Create Tender',
        action: 'create',
        description: 'Create new tenders.',
        displayOrder: 2,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },

    {
        key: 'tender.update',
        name: 'Update Tender',
        action: 'update',
        description: 'Edit existing tenders.',
        displayOrder: 3,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },

    {
        key: 'tender.delete',
        name: 'Delete Tender',
        action: 'delete',
        description: 'Soft delete tenders.',
        displayOrder: 4,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },

    {
        key: 'tender.restore',
        name: 'Restore Tender',
        action: 'restore',
        description: 'Restore previously deleted tenders.',
        displayOrder: 5,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },

    {
        key: 'tender.publish',
        name: 'Publish Tender',
        action: 'publish',
        description: 'Publish draft tenders.',
        displayOrder: 6,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },

    {
        key: 'tender.unpublish',
        name: 'Unpublish Tender',
        action: 'unpublish',
        description: 'Move published tenders back to draft.',
        displayOrder: 7,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },

    {
        key: 'tender.approve',
        name: 'Approve Tender',
        action: 'approve',
        description: 'Approve tenders awaiting review.',
        displayOrder: 8,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },

    {
        key: 'tender.reject',
        name: 'Reject Tender',
        action: 'reject',
        description: 'Reject tenders awaiting approval.',
        displayOrder: 9,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },

    {
        key: 'tender.archive',
        name: 'Archive Tender',
        action: 'archive',
        description: 'Archive completed or expired tenders.',
        displayOrder: 10,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },

    {
        key: 'tender.upload_document',
        name: 'Upload Documents',
        action: 'upload',
        description: 'Upload tender related documents.',
        displayOrder: 11,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },

    {
        key: 'tender.delete_document',
        name: 'Delete Documents',
        action: 'delete_document',
        description: 'Delete tender related documents.',
        displayOrder: 12,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },

    {
        key: 'tender.export',
        name: 'Export Tenders',
        action: 'export',
        description: 'Export tender data.',
        displayOrder: 13,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },

    {
        key: 'tender.audit',
        name: 'View Tender Audit',
        action: 'audit',
        description: 'View tender audit history.',
        displayOrder: 14,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },
];